name: health_and_safe
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  characters: ^1.4.1
  material_color_utilities: ^0.13.0
  meta: ^1.17.0

dev_dependencies:
  test_api: ^0.7.7

flutter:
  uses-material-design: true
