name: health_and_safe
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter: 
    sdk: flutter
  characters: ^1.4.0
  material_color_utilities: ^0.11.1
  meta: 1.16.0

dev_dependencies:
  test_api: ^0.7.7

flutter:
  uses-material-design: true
